# Generated by Django 4.2.3 on 2023-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dubbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='animename',
            name='genres',
        ),
        migrations.AddField(
            model_name='anime',
            name='dubbing',
            field=models.ManyToManyField(related_name='animes', to='anim.dubbing'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='anim.genre'),
        ),
    ]
