# Generated by Django 4.2.3 on 2023-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0002_dubbing_genre_remove_animename_genres_anime_dubbing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
