# Generated by Django 4.2.3 on 2023-07-28 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anim', '0005_animename_remove_manga_dubbing_remove_manga_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
