# Generated by Django 4.2.3 on 2023-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='anim.genre'),
        ),
    ]
