# Generated by Django 4.2.1 on 2023-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anim', '0002_remove_anime_genres_anime_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Смотрю', 'Смотрю'), ('Просмотрено', 'Просмотрено'), ('Бросил', 'Бросил')], default='Просмотрено', max_length=250),
        ),
    ]
